name: Teardown

on:
  schedule:
    - cron: "0 12 * * *"
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
env:
  ARM_SKIP_PROVIDER_REGISTRATION: true
  ARM_USE_OIDC: true
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}

jobs:
  teardown-infrastructure:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-terraform
      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Terraform apply
        run: terraform apply -auto-approve

  clean_storage_containers:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: flush containers
        env:
          AZURE_ACCOUNT_NAME: ${{secrets.AZURE_ACCOUNT_NAME}}
          AZURE_ACCESS_KEY: ${{secrets.AZURE_ACCESS_KEY}}
          AZURE_PRIVATE_CONTAINER: ${{secrets.AZURE_PRIVATE_CONTAINER}}
          AZURE_PUBLIC_CONTAINER: ${{secrets.AZURE_PUBLIC_CONTAINER}}
          AZURE_PRINCIPAL_ID: ${{secrets.AZURE_PRINCIPAL_ID}}
        run: bundle exec rake flush_test_container
